/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;


/**
 *
 * @author cjz
 */
public class orderP extends javax.swing.JPanel {

    /**
     * Creates new form orderP
     */
    private JPanel userProcessContainer;
    private UserAccount ua;
    private EcoSystem system;
    private Manager m;
    private Restaurant res;
    private DefaultTableModel model1;
    private DefaultTableModel model2;
    private DefaultTableModel model3;
    private int selected1;
    private int selected2;
    public orderP(JPanel userProcessContainer, UserAccount ua,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.system = system;
        m = (Manager) ua.getPerson();
        res = m.getRes();
        model1 = (DefaultTableModel) jTable1.getModel();
        model2 = (DefaultTableModel) jTable2.getModel();
        model3 = (DefaultTableModel) jTable3.getModel();
        model1.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);
        refresh();
    }
        public void refresh(){
        for (Map.Entry<Integer,Order> entry : res.getOrders().getOlist().entrySet()){
            Order or = entry.getValue();
            if (or.getStatus().equals("Finished") || or.getStatus().equals("Refused") || or.getStatus().equals("Delivering"))
            {
            Object[] row = new Object[6];
            int id = or.getId();
            String content = or.getContent();
            String customer = or.getCustomer().getName();
            String status = or.getStatus();
            String comment = or.getComment();
            String de;
            if (or.getStatus().equals("Finished") || or.getStatus().equals("Delivering"))
                de = or.getDeliveryman().getName();
            else
                de = "";
            row[0] = id;
            row[1] = content;
            row[2] = de;
            row[3] = customer;
            row[4] = status;
            row[5] = comment;
            model1.addRow(row);}
            
            else {
                Object[] row = new Object[2];
                int id = or.getId();
                String content = or.getContent();
                row[0] = id;
                row[1] = content;
                model2.addRow(row);
            }   
        }
        for (Map.Entry<Integer,DeliveryMan> entry :system.getDeliveryManDirectory().getDelivermen().entrySet()){
            DeliveryMan de = entry.getValue();
            int id = de.getId();
            String name = de.getName();
            int cnt = de.unfinished();
            Object[] row = new Object[3];
            row[0] = id;
            row[1] = name;
            row[2] = cnt;
            model3.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderselected = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        deliverymanselected = new javax.swing.JLabel();
        chbtn1 = new javax.swing.JButton();
        rebtn = new javax.swing.JButton();
        chbtn2 = new javax.swing.JButton();
        asbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "order", "deliveryman", "customer", "status", "comment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "oder"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "deliveryman", "tasks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Assigned");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Pending");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Order Selected");

        orderselected.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        d.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        d.setText("Deliveryman Selected");

        deliverymanselected.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        chbtn1.setText("Choose");
        chbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbtn1ActionPerformed(evt);
            }
        });

        rebtn.setText("Refuse");
        rebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rebtnActionPerformed(evt);
            }
        });

        chbtn2.setText("Choose");
        chbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbtn2ActionPerformed(evt);
            }
        });

        asbtn.setText("Assign");
        asbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asbtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(35, 35, 35)
                                        .addComponent(orderselected, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(asbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(d)
                                .addGap(18, 18, 18)
                                .addComponent(deliverymanselected, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbtn1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chbtn2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(orderselected, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d)
                        .addComponent(deliverymanselected, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(asbtn)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbtn1ActionPerformed
        // TODO add your handling code here:
        int selected = jTable2.getSelectedRow();
        orderselected.setText(String.valueOf(model2.getValueAt(selected, 0)));
        this.selected1 = selected;
        
    }//GEN-LAST:event_chbtn1ActionPerformed

    private void rebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rebtnActionPerformed
        // TODO add your handling code here:
        int selected = jTable2.getSelectedRow();
        Order or = res.getOrders().getOlist().get(model2.getValueAt(selected, 0));
        or.setStatus("Refused");
        model2.removeRow(selected);
        Object[] row = new Object[6];
        row[0] = or.getId();
            row[1] = or.getContent();
            row[2] = "";
            row[3] = or.getCustomer().getName();
            row[4] = or.getStatus();
            row[5] = or.getComment();
            model1.addRow(row);
            JOptionPane.showMessageDialog(this, "Refused.");
        
    }//GEN-LAST:event_rebtnActionPerformed

    private void chbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbtn2ActionPerformed
        // TODO add your handling code here:
        int selected = jTable3.getSelectedRow();
        deliverymanselected.setText(String.valueOf(model3.getValueAt(selected, 0)));
        selected2 = selected;
    }//GEN-LAST:event_chbtn2ActionPerformed

    private void asbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asbtnActionPerformed
        // TODO add your handling code here:
        int orid = Integer.valueOf(orderselected.getText().toString());
        int deid = Integer.valueOf(deliverymanselected.getText().toString());
        Order or = res.getOrders().getOlist().get(orid);
        DeliveryMan de = system.getDeliveryManDirectory().getDelivermen().get(deid);
        or.setStatus("Delivering");
        or.setDeliveryman(de);
        de.getOrders().getOlist().put(orid, or);
        model2.removeRow(selected1);
        model3.setValueAt(de.unfinished(), selected2, 2);
        Object[] row = new Object[6];
        row[0] = or.getId();
            row[1] = or.getContent();
            row[2] = or.getDeliveryman().getName();
            row[3] = or.getCustomer().getName();
            row[4] = or.getStatus();
            row[5] = or.getComment();
        model1.addRow(row);
        JOptionPane.showMessageDialog(this, "Assigned.");
    }//GEN-LAST:event_asbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asbtn;
    private javax.swing.JButton chbtn1;
    private javax.swing.JButton chbtn2;
    private javax.swing.JLabel d;
    private javax.swing.JLabel deliverymanselected;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel orderselected;
    private javax.swing.JButton rebtn;
    // End of variables declaration//GEN-END:variables
}
